helloworld/hello/urls.py
from django.urls import path
from . import views
app_name = "hello"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),

]

helloworld/helloworld/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('flights/', include("flights.urls")),
    path('users/', include("users.urls")),
    path('temp/', include("temp.urls")),
]

helloworld/temp/urls.py
from django.urls import path
from . import views
app_name = "temp"
urlpatterns = [
    path("", views.index, name="index"),
    path("contact", views.contact, name="contact"),
    path("feature", views.feature, name="feature"),
    path("preattck", views.preattck, name="preattck"),
    path("mobile", views.mobile, name="mobile"),
    path("news", views.news, name="news"),
    path("about", views.about, name="about"),
    path("post", views.post, name="post"),
    path("register", views.register, name="register"),
    path("registerform", views.registerform, name="registerform"),
    path("logging", views.logging, name="logging"),
    path("log_out", views.log_out, name="log_out"),
    path("mitrematrix", views.mitrematrix, name="mitrematrix"),
    path('activate/<uidb64>/<token>/', views.activate, name="activate"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("updatemitre", views.updatemitre, name="updatemitre"),
    path("subscription", views.subscription, name="subscription"),
    path("hypothesis", views.hypothesis, name="hypothesis"),
    path("ai", views.ai, name="ai"),
    path("emulate", views.emulate, name="emulate"),
    path("makeadversary", views.makeadversary, name="makeadversary"),
    path("certification", views.certification, name="certification"),
    path("actioncollaboration", views.actioncollaboration, name="actioncollaboration"),
    path("adversarycollaboration", views.adversarycollaboration, name="adversarycollaboration"),
    path("experiencecollaboration", views.experiencecollaboration, name="experiencecollaboration"),
]

helloworld/temp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    """
      Form for Registering new users
    """
    email = forms.EmailField(max_length=60, help_text = 'Required. Add a valid email address')
    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        """
          specifying styles to fields
        """
        super(RegistrationForm, self).__init__(*args, **kwargs)
        for field in (self.fields['email'],self.fields['username'],self.fields['password1'],self.fields['password2']):
            field.widget.attrs.update({'class': 'form-control '})


class AccountAuthenticationForm(forms.ModelForm):
    """
      Form for Logging in  users
    """
    password  = forms.CharField(label= 'Password', widget=forms.PasswordInput)

    class Meta:
        model  =  User
        fields =  ('email', 'password')
        widgets = {
                   'email':forms.TextInput(attrs={'class':'form-control'}),
                   'password':forms.TextInput(attrs={'class':'form-control'}),
        }
    def __init__(self, *args, **kwargs):
        """
          specifying styles to fields
        """
        super(AccountAuthenticationForm, self).__init__(*args, **kwargs)
        for field in (self.fields['email'],self.fields['password']):
            field.widget.attrs.update({'class': 'form-control '})

    def clean(self):
        if self.is_valid():

            email = self.cleaned_data.get('email')
            password = self.cleaned_data.get('password')
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid Login')

class AccountUpdateform(forms.ModelForm):
    """
      Updating User Info
    """
    class Meta:
        model  = User
        fields = ('email', 'username')
        widgets = {
                   'email':forms.TextInput(attrs={'class':'form-control'}),
                   'password':forms.TextInput(attrs={'class':'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        """
          specifying styles to fields
        """
        super(AccountUpdateform, self).__init__(*args, **kwargs)
        for field in (self.fields['email'],self.fields['username']):
            field.widget.attrs.update({'class': 'form-control '})

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                account = User.objects.exclude(pk = self.instance.pk).get(email=email)
            except User.DoesNotExist:
                return email
            raise forms.ValidationError("Email '%s' already in use." %email)
    def clean_username(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            try:
                account = User.objects.exclude(pk = self.instance.pk).get(username=username)
            except User.DoesNotExist:
                return username
            raise forms.ValidationError("Username '%s' already in use." % username)

helloworld/temp/views.py
from django.contrib.auth import login, logout, authenticate
from .models import contactmodel, blog, technique, TACTIC, malware, actor, emulation, useratt, customadversary, actionsofadversary, userans, exam

from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django_email_verification import send_email
from django.core.mail import EmailMessage
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import default_token_generator
from pyattck import Attck
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from .forms import RegistrationForm
import socket
from django.contrib.auth import get_user_model
# Create your views here.

def index(request):
    form = RegistrationForm()
    flag = False
    if not request.user.is_authenticated:
        flag = True
    return render(request, "temp/index.html",{
        "flag": flag,
        "form": form
    })

def contact(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    if request.method == "POST":
        # form = contactform(request.POST)
        # if form.is_valid():
            # name = form.cleaned_data["name"]
            # email = form.cleaned_data["email"]
            # subject = form.cleaned_data["subject"]
            # desc = form.cleaned_data["desc"]
            name = request.POST["name"]
            email = request.POST["email"]
            subject = request.POST["subject"]
            desc = request.POST["desc"]
            f = contactmodel(name=name, email=email, subject=subject, desc=desc, readed=False)
            f.save()
            return render(request, "temp/contact.html", {
                "flag": flag
            })
    else:
            # return render(request, "temp/contact.html",{
            #     "form": form
            # })
            return render(request, "temp/contact.html", {
                "flag": flag
    })
def feature(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    attack = Attck()
    return render(request, "temp/features.html", {
        "flag": flag,
        'attack': attack
    })

def preattck(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    attack = Attck()
    return render(request, "temp/preattck.html", {
        "flag": flag,
        'attack': attack
    })

def mobile(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    attack = Attck()
    return render(request, "temp/mobile.html", {
        "flag": flag,
        'attack': attack
    })

def mitrematrix(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    return render(request, "temp/compass.html",{
        "flag": flag
    })

def news(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    page = 1
    page = request.GET.get('page')
    allposts = blog.objects.all()
    # use Django's pagination
    # https://docs.djangoproject.com/en/dev/topics/pagination/
    results_per_page = 5
    paginator = Paginator(allposts, results_per_page)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    # build a html posts list with the paginated posts
    return render(request, 'temp/news.html', {
        'posts': posts,
        'flag': flag,
        'page': page
    })

def about(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    posts = blog.objects.all()
    return render(request, "temp/about.html", {
        "flag": flag
    })

def post(request, pk):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    content = blog.objects.get(pk=pk)
    content.totalread = content.totalread + 1
    context = {
        'content': content
    }
    return render(request, "temp/{{ pk }}.html", {
        "flag": flag,
        "content": content
    })

def register(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    form = RegistrationForm(request.POST)
    message = "You can simply register in our website. Just fill out the following form and click on submit."
    if request.method == "POST":
        name = request.POST["username"]
        useremail = request.POST["email"]
        password = request.POST["password1"]
        confirmpassword = request.POST["password2"]
        if password == confirmpassword:
            # try:
                user = User.objects.create_user(name, useremail, password)
                user.is_active = False  # Example
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Activate your account.'
                message = render_to_string('temp/acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': default_token_generator.make_token(user),
                })
                email = EmailMessage(
                    mail_subject, message, to=[useremail]
                )
                email.send()
                return HttpResponse('Please confirm your email address to complete the registration')
            # except:
                message = "The email or username has already existed"
                return render(request, "temp/login.html", {
                    "message": message,
                    "flag": flag,
                    "form": form
                })
        else:
            message = "Password does not match"
            return render(request, "temp/login.html", {
                "message": message,
                "flag": flag,
                "form": form
            })

    else:
        # return render(request, "temp/contact.html",{
        #     "form": form
        # })
        return render(request, "temp/login.html", {
            "message": message,
            "flag": flag,
            "form": form,
    })

def registerform(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("")
    else:
        form = RegisterForm()
        return render(response, "",
            {
                "form":form
        })

def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse("temp:index"))

def logging(request):
    if request.method == "POST":
        email = request.POST["username"]
        password = request.POST["password"]
        username = User.objects.get(email=email)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("temp:index"), {
                "message": "Valid credentials"
            })
        else:
            return render(request, "temp/index.html", {
                "message": "Invalid credentials."
            })

    return HttpResponseRedirect(reverse("temp:index"))

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

def post_detail(request, pk):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    content = blog.objects.get(pk=pk)
    content.totalread = content.totalread + 1
    content.save()
    return render(request, "temp/post.html", {
        "flag": flag,
        "content": content
    })

def lazy_load_posts(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    page = request.POST.get('page')
    posts = blog.objects.all()
    # use Django's pagination
    # https://docs.djangoproject.com/en/dev/topics/pagination/
    results_per_page = 2
    paginator = Paginator(posts, results_per_page)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    # build a html posts list with the paginated posts
    posts_html = loader.render_to_string(
        'temp/post.html',

        {'posts': posts,
         'flag': flag
         }
    )
    # package output data and return it as a JSON object
    output_data = {
        'posts_html': posts_html,
        'flag': flag,
        'has_next': posts.has_next()
    }
    return JsonResponse(output_data)

def updatemitre(request):
    flag = False
    if not request.user.is_authenticated:
        flag = True
    if request.method == "POST":
        attack = Attck()
        # emulation.objects.all().delete()
        # for tactic in attack.enterprise.tactics:
        #     for technique in tactic.techniques:
        #         q = emulation()
        #         q.ability = "(" + tactic.id + " " + tactic.name + ")" + " " + technique.id + " " + technique.name
        #         q.save()
        # p = TACTIC.objects.order_by('identifier')

helloworld/temp/templates/temp/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'temp:activate' uidb64=uid token=token %}
If you think, it's not you, then just ignore this email.
{% endautoescape %}

helloworld/temp/templates/temp/certification.html
{% extends 'temp/layout.html' %}
{% load static %}
{% block body %}
    <div id="contents">
        <form method="POST">
            {% csrf_token %}
            <h3 class="question">{{question.question}}</h3>
            <input type="radio" name="choise1" class="radio" id="1">
            <label class="radio">{{question.firstchoice}}</label><br>
            <input type="radio" name="choise2" class="radio" id="2">
            <label class="radio">{{question.secondchoice}}</label><br>
            <input type="radio" name="choise3" class="radio"id="3">
            <label class="radio">{{question.thirdchoice}}</label><br>
            <input type="radio" name="choise4" class="radio" id="4">
            <label class="radio">{{question.fourthchoice}}</label><br>
            {% if first == False %}
            <input type="submit" value="PREVIOUS" class="certbtn" name="PREVIOUS">
            {% endif %}
            {% if last %}
            <input type="submit" value="FINISH" class="certbtn" name="FINISH">
            {% else %}
            <input type="submit" value="NEXT" class="certbtn" name="NEXT">
            {% endif %}

        </form>
    </div>
{% endblock %}

helloworld/temp/templates/temp/compass.html
{% extends "temp/layout.html" %}
{% load static %}
{% block body %}

<div id="compass-section-1" class="section-profile">
    <div class="row" style="background-color: inherit;">
        <iframe src="https://mitre-attack.github.io/attack-navigator/enterprise/"
                style="display:flex;width:95%;border-radius:25px;background-color: white;overflow:auto;height:1500px;border:5px solid black; margin: 0 auto;">
        </iframe>
    </div>
</div>

<script src="{% static 'js/compass.js' %}"></script>`
{% endblock %}

helloworld/temp/templates/temp/contact.html
{% extends "temp/layout.html" %}
{% load static %}
{% block body %}
	<div id="contents">
		<div class="section">
			<h1>Drop us a line.</h1>
			<p>
				We'd loved to hear from you.
			</p>
			<form action="{% url 'temp:contact' %}" method="POST" class="message">
				{% csrf_token %}
				<input type="text" placeholder="Name" name="name" onFocus="this.select();" onMouseOut="javascript:return false;" required/>
				<input type="email" placeholder="Email Address" name="email" onFocus="this.select();" onMouseOut="javascript:return false;" required/>
				<input type="text" placeholder="Subject" name="subject" onFocus="this.select();" onMouseOut="javascript:return false;" required/>
				<textarea name="desc"></textarea>
				<input type="submit" value="Send"/>
			</form>
		</div>
	</div>
{% endblock %}

helloworld/temp/templates/temp/emulate.html
{% extends "temp/layout.html" %}
{% load static %}
{% block body %}

<div id="contents">

    {% if status %}
        <h1>Agent is connected</h1>
    {% endif %}
    {% if status == False %}
        <h1>Agent is disconnected</h1>
    {% endif %}
       <form name="form0" id="form0" action="" class="form0" method="POST">
           {% csrf_token %}
           {% if serverstatus == False %}
               <h1>{{ message }} <a href="{% static 'temp/agent.exe' %}">this link:</a></h1>
               <input name="run" type="submit" value="Start" onclick="waitingclient()">
               <h1 id="waitingclient" style="display:none;">Waiting for client to connect...</h1>

           {% endif %}
           {% if serverstatus %}
               <h1>{{ message }}</h1>
               <input name="stop" type="submit" value="Stop">
           {% endif %}
       </form>

       <form name="form1" id="form1" action="" class="form1" method="POST">
            {% csrf_token %}
          <select name="tactic" id="tactic" required>
            <option value="" selected="selected">Choose a Tactics</option>
          </select>
          <select name="technique" id="technique" required>
            <option value="" selected="selected">Choose a technique</option>
          </select>

          <select name="action" id="action" required>
            <option value="" selected="selected">Choose an action</option>
          </select>
          <input name="form1" type="submit" value="Run">
       </form>
<!--    <form name="form3" id="form3" action="" class="form3" method="POST">-->
<!--            {% csrf_token %}-->
<!--          <select name="adversary" id="adversary" required>-->
<!--            <option value="" selected="selected">Choose an adversary</option>-->
<!--            <option value="">REvil</option>-->
<!--          </select>-->
<!--          <input name="form3" type="submit" value="Run">-->
<!--       </form>-->
       <form name="form2" id="form2" action="" class="form2" method="POST">
          {% csrf_token %}
          <input id="manualcommand" value="" type="text" name="command" required placeholder="Enter your command...">
          <input name="mannualcommand" type="submit" value="Run">
       </form>
    <div class="adversaryresults">
        <table>
            <th>Tactic</th>
            <th>Technique</th>
            <th>Action</th>
            <th>Command</th>
            <th>Possible Detection</th>
            <th>Result</th>

            <tr>
                {% for item in result %}
                <td>{{ item }}</td>
                {% endfor %}
		    </tr>

        </table>
<!--        <p>-->
<!--            {{ command }}-->
<!--        </p>-->
<!--        {% for item in result %}-->
<!--            <p>-->
<!--			{{ item }}-->
<!--		    </p>-->
<!--            <a>&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</a>-->
<!--        {% endfor %}-->
<!--        <p>-->
<!--            {{ possibledetection }}-->
<!--		</p>-->
    </div>

</div>
<script>
var subjectObject = {
  "Discovery": {
    "System owner/user discovery": ["Current user", "Identify active user", "Gat admin members", "Get service accounts", "System owner/user discovery"],
    "CSS": ["Borders", "Margins", "Backgrounds", "Float"],
    "JavaScript": ["Variables", "Operators", "Functions", "Conditions"]
  },
  "Back-end": {
    "PHP": ["Variables", "Strings", "Arrays"],
    "SQL": ["SELECT", "UPDATE", "DELETE"]
  }
}
window.onload = function() {
  var subjectSel = document.getElementById("tactic");
  var topicSel = document.getElementById("technique");
  var chapterSel = document.getElementById("action");
  for (var x in subjectObject) {
    subjectSel.options[subjectSel.options.length] = new Option(x, x);
  }
  subjectSel.onchange = function() {
    //empty Chapters- and Topics- dropdowns
    chapterSel.length = 1;
    topicSel.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      topicSel.options[topicSel.options.length] = new Option(y, y);
    }
  }
  topicSel.onchange = function() {
    //empty Chapters dropdown
    chapterSel.length = 1;
    //display correct values
    var z = subjectObject[subjectSel.value][this.value];
    for (var i = 0; i < z.length; i++) {
      chapterSel.options[chapterSel.options.length] = new Option(z[i], z[i]);
    }
  }
}
var waitingclient = function() {

    document.getElementById('waitingclient').style.display = "block";
}
</script>
{% endblock %}

helloworld/temp/templates/temp/experiencecollaboration.html
{% extends "temp/layout.html" %}
{% load static %}
{% block body %}
    <div id="contents">
		<div class="section">
			<h1>Share your experience.</h1>
			<p>
				All cyber security professionals would loved to hear from you.
			</p>
			<form action="{% url 'temp:contact' %}" method="POST" class="message">
				{% csrf_token %}
				<input type="text" placeholder="Subject" name="subject" onFocus="this.select();" onMouseOut="javascript:return false;" required/>
				<textarea name="desc"></textarea>
				<input type="submit" value="Share"/>
			</form>
		</div>
	</div>
{% endblock %}

helloworld/temp/templates/temp/login.html
{% extends "temp/layout.html" %}
{% load static %}
{% block body %}
	<div id="contents">
		<div>
<!--			<h1>Register</h1>-->
			<h1>{{ message }}</h1>
<!--			<p>-->
<!--				You can simply register in our website. Just fill out the following form and click on submit.-->
<!--			</p>-->
			<form action="{% url 'temp:register' %}" method="POST" class="message">
				{% csrf_token %}
<!--				<input type="text" placeholder="Name" name="name" onFocus="this.select();" onMouseOut="javascript:return false;" required />-->
<!--				<input type="email" placeholder="Email" name="email" onFocus="this.select();" onMouseOut="javascript:return false;" required/>-->
<!--				<input type="password" placeholder="Enter Password" name="password" id="password" onFocus="this.select();" onMouseOut="javascript:return false;" onkeyup='passwordChanged();' required/>-->
<!--				<input type="password" placeholder="Confirm Password"  name="confirmpassword" id="confirmpassword" onFocus="this.select();" onMouseOut="javascript:return false;" onkeyup='check();' required/>-->
				{{ form }}
				<input type="submit" value="Submit"/>
			</form>
		</div>

	</div>
{% endblock %}

helloworld/temp/templates/temp/news.html
{% extends "temp/layout.html" %}
{% load static %}
{% block body %}
	<div id="contents">
		<div class="main">
			<h1>News</h1>

			<ul class="news">
				{% for post in posts %}
				<li>
<!--					<div class="date">-->
<!--						<p>-->
<!--							<span>{{ post.month }}</span>-->
<!--							{{ post.year }}-->
<!--						</p>-->
<!--					</div>-->
					<h2>{{ post.topic}}<span>{{ post.reference }}</span></h2>
					<p>
						{{ post.content | slice:":255"}}... <span><a href="{% url 'temp:post_detail' post.pk%}" class="more">Read More</a></span>
					</p>
				</li>
				{% endfor %}
			</ul>
			<div class="pagination">
				<span class="step-links">
					{% if posts.has_previous %}
						<a href="?page=1">&laquo; first</a>
						<a href="?page={{ posts.previous_page_number }}">previous</a>
					{% endif %}
					{% if posts.has_previous == False %}
						<a>&laquo; first</a>
						<a>previous</a>
					{% endif %}

					<span class="current">
						<a>Page {{ posts.number }} of {{ posts.paginator.num_pages }}.</a>
					</span>

					{% if posts.has_next %}
						<a href="?page={{ posts.next_page_number }}">next</a>
						<a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
					{% endif %}
					{% if posts.has_next == False %}
						<a>next</a>
						<a>last &raquo;</a>
					{% endif %}
				</span>
			</div>
		</div>
		<div class="sidebar">
			<h1>Popular Posts</h1>
			<ul class="posts">
				<li>
					<h4 class="title"><a href="{% url 'temp:post' %}">Making It Work</a></h4>
					<p>
						I'm a paragraph. Click here to add your own text and edit me. I’m a great place for you to tell a story and let your users know a little more about you.
					</p>
				</li>
				<li>
					<h4 class="title"><a href="{% url 'temp:post' %}">Designs and Concepts</a></h4>
					<p>
						I'm a paragraph. Click here to add your own text and edit me. I’m a great place for you to tell a story and let your users know a little more about you.
					</p>
				</li>
				<li>
					<h4 class="title"><a href="{% url 'temp:post' %}">Getting It Done!</a></h4>
					<p>
						I'm a paragraph. Click here to add your own text and edit me. I’m a great place for you to tell a story and let your users know a little more about you.
					</p>
				</li>
			</ul>
		</div>
	</div>
{% endblock %}

helloworld/temp/templates/temp/post.html
{% extends "temp/layout.html" %}
{% load static %}
{% block body %}
	<div id="contents">
		<div class="post">
<!--			<div class="date">-->
<!--				<p>-->
<!--					<span>03</span>-->
<!--					2023-->
<!--				</p>-->
<!--			</div>-->
			<h1>{{ content.topic}}<span class="author">{{ content.reference }}</span></h1>
<!--			<img id="postpic" src="{% static 'temp/images/logo.png' %}" alt="Img">-->
			<img id="postpic" src="{% static 'temp/images/{{content.img.url}}' %}" alt="Img">
<!--			<img id="postpic" src="{{content.img.url}}">-->
<!--			{{content.img.url}}-->
			<p>
				{{ content.content | linebreaks }}
			</p>
			<span><a href="{% url 'temp:news' %}" class="more">Back to News</a></span>
		</div>
	</div>
{% endblock %}

helloworld/temp/templates/temp/pyattack.html
{% extends "temp/layout.html" %}
{% block body %}
    <h1>Hello, This is the list of TTPs</h1>
        <ul>List of TTPs</ul>
        {% for flight in flights %}
            <li>{{ flight }}</li>
        {% endfor %}
        <a href="{% url 'temp:add' %}">Add flight</a>
{% endblock %}

helloworld/temp/templates/temp/updatemitre.html
{% extends 'temp/layout.html' %}
{% load static %}
{% block body %}
            {% if flag %}
			<p>
				You have to login to use this feature. Please login or register via corner box of the site.
			</p>
            {% endif %}
			{% if flag == False %}

            <form action="{% url 'temp:updatemitre' %}" method="POST">
                {% csrf_token %}
                <input type="submit" method="POST" >Update Mitre Matrix </input>
            </form>
			{% endif %}
{% endblock %}